### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by danielmichaels** [danielmichaels/http-tracer#4]
# Output Data

Add output option rather than just to stdout.

Types that require implementation:

- [ ] CSV
- [ ] JSON
- [ ] Plaintext

**Comment by haydencordeiro** [comment]
What if we do something like this
import sys
orig_stdout = sys.stdout
f = open('out.txt', 'w')
sys.stdout = f

To store the output into a file?

**Comment by danielmichaels** [comment]
Hey,

Thanks for raising the issue before the PR. Happy for you to create a PR with your proposed changes.

Without much to go on other than your snippet, I would suggest you wrap any file operations in a context manager such as:

```python
# name needs to be a flag in the CLI
with open(f"{name}", w) as f:
    ..do write operations here..
```
So its obvious to the user, the output path needs to be supplied by them through a CLI flag.

Here is the output of `http-tracer --help`:

```sh
❯ http-tracer --help
Usage: http-tracer [OPTIONS] URL

  HTTP-Tracer returns the redirects on way to the destination URL.

  If user does not supply 'https://' it will default to 'http://'

Options:
  -f, --full  Print detailed report on each hop along the path
  --help      Show this message and exit.
```

A new option of `-o, --output` should correspond with the ability to write the output to disk.

Cheers
